//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TT_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanTool
    {
        public int LoanToolID { get; set; }
        public int LoanID { get; set; }
        public int ToolID { get; set; }
    
        public virtual Loan Loan { get; set; }
        public virtual Tool Tool { get; set; }
    }
}
